name: Docker Build & Publish

on:
  release:
    types: [published]
  workflow_run:
    workflows: ["Release"]
    branches: [main]
    types: [completed]

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    # Only run if the release workflow completed successfully or a release was published
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'release' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: watercrawl/mcp
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=short
            latest
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Check if Docker Hub secrets exist
        id: check-secrets
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "has_docker_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "has_docker_secrets=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        # Only run this step if Docker Hub credentials are available
        if: steps.check-secrets.outputs.has_docker_secrets == 'true'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          # Only push if Docker Hub credentials are available
          push: ${{ steps.check-secrets.outputs.has_docker_secrets == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
